"""情绪音效配置（2026-04-22 更新：低覆盖桶词汇替代优化，优先冲击 >=5 条可用量）。"""

from typing import Dict, List


MOOD_PROFILES: Dict[str, Dict[str, List[str] | str]] = {
    "warm": {
        "name": "温暖",
        "search_terms": [
            "warm ambient atmosphere",
            "cozy cinematic background",
            "gentle warm drone",
            "soft warm pad ambience",
            "comforting background atmosphere",
            "warm emotional cinematic",
            "intimate ambient texture",
            "warm room tone soundtrack",
        ],
    },
    "calm": {
        "name": "平静",
        "search_terms": [
            "calm ambient background",
            "peaceful atmosphere cinematic",
            "serene drone ambience",
            "minimal calm underscore",
            "soft neutral background music",
            "quiet contemplative ambient",
            "slow calm texture",
            "relaxed cinematic atmosphere",
        ],
    },
    "playful": {
        "name": "俏皮",
        "search_terms": [
            "playful ambient background",
            "light whimsical cinematic",
            "quirky atmosphere soundtrack",
            "fun curious underscore",
            "bouncy playful texture",
            "mischievous ambient loop",
            "lighthearted cinematic background",
            "cheerful playful atmosphere",
        ],
    },
    "romantic": {
        "name": "浪漫",
        "search_terms": [
            "romantic ambient atmosphere",
            "romantic cinematic background",
            "tender emotional underscore",
            "soft love theme ambient",
            "intimate romantic texture",
            "dreamy romantic pad",
            "gentle romantic soundtrack",
            "warm romantic atmosphere",
        ],
    },
    "dreamy": {
        "name": "梦幻",
        "search_terms": [
            "dreamy ambient atmosphere",
            "ethereal cinematic background",
            "floating dream pad",
            "surreal ambient texture",
            "hazy dreamscape soundtrack",
            "dreamlike atmosphere drone",
            "soft airy cinematic",
            "fantasy ambient background",
        ],
    },
    "lonely": {
        "name": "孤独",
        "search_terms": [
            "lonely ambient atmosphere",
            "isolated cinematic background",
            "empty room tone ambience",
            "solitude drone underscore",
            "distant lonely texture",
            "bleak ambient background",
            "abandoned place atmosphere",
            "quiet lonely cinematic",
        ],
    },
    "melancholic": {
        "name": "忧郁",
        "search_terms": [
            "melancholic ambient atmosphere",
            "sad cinematic background",
            "somber drone texture",
            "emotional melancholic underscore",
            "moody ambient soundtrack",
            "dark melancholic pad",
            "bittersweet cinematic atmosphere",
            "slow melancholic background",
        ],
    },
    "regretful": {
        "name": "遗憾",
        "search_terms": [
            "remorseful ambient atmosphere",
            "guilt cinematic background",
            "wistful sorrow ambient",
            "lament emotional drone",
            "sad aftermath ambience",
            "apology regret underscore",
            "melancholy remorse texture",
            "bittersweet loss atmosphere",
            "tragic reflection background",
            "regret piano ambient",
            "forlorn emotional pad",
            "sorrowful aftermath soundtrack",
        ],
        "match_terms": [
            "regret",
            "remorse",
            "remorseful",
            "guilt",
            "sorrow",
            "lament",
            "aftermath",
            "loss",
            "forlorn",
            "wistful",
        ],
    },
    "hopeful": {
        "name": "希望",
        "search_terms": [
            "hopeful ambient atmosphere",
            "optimistic cinematic background",
            "gentle hopeful underscore",
            "bright emotional texture",
            "healing ambient soundtrack",
            "positive atmospheric pad",
            "soft uplifting hope",
            "hopeful resolution ambience",
        ],
    },
    "uplifting": {
        "name": "振奋",
        "search_terms": [
            "uplifting ambient atmosphere",
            "uplifting cinematic background",
            "inspiring underscore texture",
            "motivational atmospheric soundtrack",
            "positive uplift drone",
            "emotional rise cinematic",
            "light uplifting pad",
            "encouraging ambient background",
        ],
    },
    "triumphant": {
        "name": "凯旋",
        "search_terms": [
            "victory cinematic atmosphere",
            "heroic finale soundtrack",
            "triumphant fanfare ambient",
            "epic win underscore",
            "celebration orchestral background",
            "champion moment cinematic",
            "glorious ending theme",
            "conquest dramatic atmosphere",
            "victorious rise texture",
            "success anthem ambience",
            "heroic resolution soundtrack",
            "uplifted triumph background",
        ],
        "match_terms": [
            "triumph",
            "triumphant",
            "victory",
            "victorious",
            "heroic",
            "fanfare",
            "champion",
            "conquest",
            "glorious",
            "anthem",
        ],
    },
    "mysterious": {
        "name": "神秘",
        "search_terms": [
            "mysterious ambient atmosphere",
            "mystery cinematic background",
            "enigmatic drone texture",
            "dark mystery underscore",
            "investigation atmosphere soundtrack",
            "secretive ambient pad",
            "curious mysterious cinematic",
            "suspense mystery background",
        ],
    },
    "uneasy": {
        "name": "不安",
        "search_terms": [
            "uneasy ambient atmosphere",
            "restless cinematic background",
            "nervous tension drone",
            "unsettling underscore texture",
            "anxious atmospheric soundtrack",
            "ominous uneasy pad",
            "low uneasy rumble",
            "creeping tension atmosphere",
            "foreboding ambient tension",
            "paranoia cinematic underscore",
            "dread build up atmosphere",
            "subtle uneasy suspense drone",
        ],
        "match_terms": ["uneasy", "unsettling", "anxious", "restless", "ominous", "foreboding", "dread"],
    },
    "suspenseful": {
        "name": "悬疑",
        "search_terms": [
            "suspenseful ambient atmosphere",
            "suspense cinematic background",
            "thriller tension underscore",
            "rising suspense drone",
            "countdown atmospheric soundtrack",
            "dark suspense pulse",
            "investigation suspense texture",
            "cinematic suspense loop",
        ],
    },
    "horrific": {
        "name": "恐怖",
        "search_terms": [
            "horrific ambient atmosphere",
            "horror cinematic background",
            "scary drone underscore",
            "terror atmosphere soundtrack",
            "creepy dark texture",
            "haunted ambient pad",
            "sinister horror rumble",
            "dreadful cinematic tension",
        ],
    },
    "urgent": {
        "name": "紧急",
        "search_terms": [
            "countdown tension cinematic",
            "emergency pulse background",
            "race against time soundtrack",
            "high stakes chase ambience",
            "critical alert atmosphere",
            "imminent danger underscore",
            "urgent thriller pulse",
            "crisis build up ambient",
            "panic countdown texture",
            "alarm urgency drone",
            "time pressure cinematic",
            "rapid tension background",
        ],
        "match_terms": [
            "urgent",
            "urgency",
            "countdown",
            "emergency",
            "critical",
            "crisis",
            "chase",
            "alarm",
            "imminent",
            "pressure",
        ],
    },
    "conflicted": {
        "name": "纠结",
        "search_terms": [
            "conflicted emotional atmosphere",
            "inner conflict cinematic background",
            "moral dilemma underscore",
            "tense emotional drone",
            "doubtful ambient texture",
            "conflicted dramatic soundtrack",
            "uncertain atmosphere pad",
            "mixed feelings cinematic",
            "inner turmoil ambient",
            "hesitation emotional tension",
            "doubt and conflict background",
            "moral struggle cinematic",
        ],
        "match_terms": ["conflict", "conflicted", "dilemma", "doubt", "uncertain", "turmoil", "struggle"],
    },
    "dramatic": {
        "name": "戏剧化",
        "search_terms": [
            "dramatic cinematic background",
            "dramatic atmosphere soundtrack",
            "intense dramatic underscore",
            "theatrical tension drone",
            "high emotion cinematic",
            "dramatic conflict texture",
            "epic drama ambient",
            "powerful dramatic build",
        ],
    },
    "revelatory": {
        "name": "揭示",
        "search_terms": [
            "truth reveal cinematic",
            "mystery solved atmosphere",
            "plot twist reveal soundtrack",
            "investigation breakthrough underscore",
            "secret uncovered ambience",
            "final clue discovery background",
            "dramatic unveil texture",
            "epiphany cinematic drone",
            "turning point atmosphere",
            "truth exposed soundtrack",
            "revelation aftermath ambient",
            "hidden fact uncovered music",
        ],
        "match_terms": [
            "reveal",
            "revelation",
            "truth",
            "unveil",
            "twist",
            "discovery",
            "breakthrough",
            "uncovered",
            "epiphany",
            "turning",
        ],
    },
    "chaotic": {
        "name": "混乱",
        "search_terms": [
            "chaotic tension cinematic",
            "frenzy atmosphere soundtrack",
            "pandemonium ambient background",
            "turmoil frantic underscore",
            "disorder panic texture",
            "out of control ambience",
            "anarchy dramatic drone",
            "breakdown unstable atmosphere",
            "riot chaos background",
            "unraveling frantic cinematic",
            "confusion overload soundtrack",
            "violent turmoil ambient",
        ],
        "match_terms": [
            "chaos",
            "chaotic",
            "frenzy",
            "pandemonium",
            "turmoil",
            "frantic",
            "panic",
            "disorder",
            "anarchy",
            "breakdown",
        ],
    },
}


DEFAULT_PHASE_TO_MOOD: Dict[str, str] = {
    "opening": "warm",
    "opening_rules": "calm",
    "discussion": "calm",
    "discussion_clue1": "uneasy",
    "discussion_clue2": "suspenseful",
    "search": "mysterious",
    "vote": "suspenseful",
    "owner_confrontation": "conflicted",
    "ending": "revelatory",
}


DEFAULT_ENDING_MOOD: Dict[str, str] = {
    "default": "revelatory",
    "happy": "triumphant",
    "bad": "regretful",
}
